server {
  listen 80;
  server_name localhost;
  root /usr/share/nginx/html;
  include /etc/nginx/mime.types;

  client_max_body_size 0;
  gzip on;

  location /dicom-web/ {
    proxy_pass http://orthanc:8042/dicom-web/;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
  }

  location /wado {
    proxy_pass http://orthanc:8042/wado;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
  }

  location / {
    try_files $uri $uri/ /index.html;
    add_header Cross-Origin-Opener-Policy same-origin;
    add_header Cross-Origin-Embedder-Policy require-corp;
  }
}
